Vamos a descargar unos ficheros grandes de una url, corresponden al servicio de taxis en Nueva York (3,4 millones de filas)
https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
descargamos los datos del taxi amarillo de enero a marzo de 2025 en formato parquet, lo pondremos en C:\PCAD
- Convertir el parquet en un csv
- Comparar el tiempo de carga entre el csv y el parquet con pandas
- Comparar el tiempo de carga entre el csv y el parquet con polars
Requisito para leer parquet debo tener instalada la libreria 
pyarrow o fastparquet >pip install pyarrow

In [2]:
#Convertir el parquet en csv
import pandas as pd
#1. Cargar el fichero parquet a un df de pandas
df = pd.read_parquet('/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/yellow_tripdata_2025-01.parquet')
#2. Obtener el numero de registros
total_registros = len(df)
#3. Guardar como .csv
df.to_csv("/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/taxis.csv", index=False)
#4. Mostar el mensaje
print("Compleato con éxito, con un total de registros de",total_registros)

Compleato con éxito, con un total de registros de 3475226

In [2]:
# Prueba de carga de los 2 ficheros tanto (.parquet como .csv) con pandas

import pandas as pd
import time
import os

# 0.path de los ficheros 

parquet_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/yellow_tripdata_2025-01.parquet'

csv_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/taxis.csv'

# 1. Medir el tiempo de carga del fichero parquet

start_parquet = time.time()
df_parquet = pd.read_parquet(parquet_file)
end_parquet = time.time()
tiempo_parquet = end_parquet - start_parquet

# 2. Medir el tiempo de carga del fichero CSV
start_csv = time.time()
df_csv = pd.read_csv(csv_file)
end_csv = time.time()
tiempo_csv = end_csv - start_csv

# 3. Mostrar los resultados

print(f"Tiempo de carga con parquet | pandas: {tiempo_parquet:.4f} segundos")

print(f"Tiempo de carga con CSV | pandas: {tiempo_csv :.4f} segundos")

/var/folders/6f/lhr87vh51bq38sm9v46389m00000gn/T/ipykernel_99272/766831991.py:22: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df_csv = pd.read_csv(csv_file)

Tiempo de carga con parquet | pandas: 0.1300 segundos
Tiempo de carga con CSV | pandas: 2.7666 segundos

In [1]:
# Prueba de carga de los 2 ficheros tanto (.parquet como .csv) con polars

import polars as pl
import time
import os

# 0.path de los ficheros 

parquet_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/yellow_tripdata_2025-01.parquet'

csv_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/taxis.csv'

# 1. Medir el tiempo de carga del fichero parquet
start_parquet = time.time()
df_parquet = pl.read_parquet(parquet_file)
end_parquet = time.time()
tiempo_parquet = end_parquet - start_parquet

# 2. Medir el tiempo de carga del fichero CSV
start_csv = time.time()
df_csv = pl.read_csv(csv_file)
end_csv = time.time()
tiempo_csv = end_csv - start_csv

# 3. Mostrar los resultados
print(f"Tiempo de carga con parquet y polars: {tiempo_parquet:.4f} segundos")

print(f"Tiempo de carga con CSV y polars: {tiempo_csv :.4f} segundos")

Tiempo de carga con parquet y polars: 0.0489 segundos
Tiempo de carga con CSV y polars: 0.1610 segundos

In [ ]:
# número de registros
len(df_parquet)

3475226

In [ ]:
# ver los primeros 50 registros
df_parquet.head(50)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0,1.60,1.0,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0,0.50,1.0,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0,0.60,1.0,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0,0.52,1.0,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0,0.66,1.0,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0
5,2,2025-01-01 00:48:24,2025-01-01 01:08:26,2.0,2.63,1.0,N,239,68,2,19.1,1.0,0.5,0.00,0.0,1.0,24.10,2.5,0.0,0.0
6,1,2025-01-01 00:14:47,2025-01-01 00:16:15,0.0,0.40,1.0,N,170,170,1,4.4,3.5,0.5,2.35,0.0,1.0,11.75,2.5,0.0,0.0
7,1,2025-01-01 00:39:27,2025-01-01 00:51:51,0.0,1.60,1.0,N,234,148,1,12.1,3.5,0.5,2.00,0.0,1.0,19.10,2.5,0.0,0.0
8,1,2025-01-01 00:53:43,2025-01-01 01:13:23,0.0,2.80,1.0,N,148,170,1,19.1,3.5,0.5,3.00,0.0,1.0,27.10,2.5,0.0,0.0
9,2,2025-01-01 00:00:02,2025-01-01 00:09:36,1.0,1.71,1.0,N,237,262,2,11.4,1.0,0.5,0.00,0.0,1.0,16.40,2.5,0.0,0.0
10,2,2025-01-01 00:20:28,2025-01-01 00:28:04,1.0,2.29,1.0,N,237,75,2,11.4,1.0,0.5,0.00,0.0,1.0,16.40,2.5,0.0,0.0
11,2,2025-01-01 00:33:58,2025-01-01 00:37:23,1.0,0.56,1.0,N,263,236,1,5.8,1.0,0.5,2.16,0.0,1.0,12.96,2.5,0.0,0.0
12,2,2025-01-01 00:42:40,2025-01-01 00:55:38,3.0,1.99,1.0,N,236,151,2,14.2,1.0,0.5,0.00,0.0,1.0,19.20,2.5,0.0,0.0
13,1,2025-01-01 00:30:07,2025-01-01 00:36:48,1.0,1.10,1.0,N,229,141,2,7.9,3.5,0.5,0.00,0.0,1.0,12.90,2.5,0.0,0.0
14,1,2025-01-01 00:39:55,2025-01-01 01:13:59,1.0,3.20,1.0,N,141,113,1,26.1,3.5,0.5,7.80,0.0,1.0,38.90,2.5,0.0,0.0
15,1,2025-01-01 00:16:54,2025-01-01 00:35:12,3.0,2.50,1.0,N,158,170,2,17.7,3.5,0.5,0.00,0.0,1.0,22.70,2.5,0.0,0.0
16,1,2025-01-01 00:43:10,2025-01-01 01:00:03,1.0,1.90,1.0,N,164,229,1,16.3,3.5,0.5,4.25,0.0,1.0,25.55,2.5,0.0,0.0
17,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,-7.2,-1.0,-0.5,3.66,0.0,-1.0,-8.54,-2.5,0.0,0.0
18,2,2025-01-01 00:01:41,2025-01-01 00:07:14,1.0,0.71,1.0,N,79,107,2,7.2,1.0,0.5,0.00,0.0,1.0,12.20,2.5,0.0,0.0
19,1,2025-01-01 00:33:12,2025-01-01 00:50:14,2.0,1.20,1.0,N,246,90,1,15.6,3.5,0.5,0.00,0.0,1.0,20.60,2.5,0.0,0.0
20,2,2025-01-01 00:05:49,2025-01-01 00:20:00,2.0,3.45,1.0,N,263,107,1,17.7,1.0,0.5,4.54,0.0,1.0,27.24,2.5,0.0,0.0
21,2,2025-01-01 00:34:40,2025-01-01 00:51:19,2.0,1.19,1.0,N,246,170,1,14.9,1.0,0.5,3.98,0.0,1.0,23.88,2.5,0.0,0.0
22,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,-6.5,-1.0,-0.5,0.00,0.0,-1.0,-11.50,-2.5,0.0,0.0
23,2,2025-01-01 00:55:54,2025-01-01 01:00:38,1.0,0.69,1.0,N,137,233,4,6.5,1.0,0.5,0.00,0.0,1.0,11.50,2.5,0.0,0.0
24,1,2025-01-01 00:17:44,2025-01-01 00:22:52,1.0,1.00,1.0,N,142,237,1,7.2,3.5,0.5,1.83,0.0,1.0,14.03,2.5,0.0,0.0
25,1,2025-01-01 00:37:13,2025-01-01 00:43:23,3.0,1.10,1.0,N,142,239,1,7.9,3.5,0.5,2.55,0.0,1.0,15.45,2.5,0.0,0.0
26,1,2025-01-01 00:48:06,2025-01-01 00:53:23,1.0,0.70,1.0,N,143,143,1,7.2,3.5,0.5,1.00,0.0,1.0,13.20,2.5,0.0,0.0
27,2,2025-01-01 00:14:14,2025-01-01 00:22:46,2.0,1.88,1.0,N,113,90,1,11.4,1.0,0.5,1.00,0.0,1.0,17.40,2.5,0.0,0.0
28,2,2025-01-01 00:32:01,2025-01-01 00:46:43,1.0,3.06,1.0,N,90,246,1,17.7,1.0,0.5,10.00,0.0,1.0,32.70,2.5,0.0,0.0
29,2,2025-01-01 00:00:37,2025-01-01 00:04:46,1.0,0.86,1.0,N,140,263,2,6.5,1.0,0.5,0.00,0.0,1.0,11.50,2.5,0.0,0.0
30,2,2025-01-01 00:11:07,2025-01-01 00:23:29,3.0,3.98,1.0,N,140,79,1,19.1,1.0,0.5,6.03,0.0,1.0,30.13,2.5,0.0,0.0
31,1,2025-01-01 00:14:54,2025-01-01 00:53:29,1.0,1.80,1.0,N,142,68,1,30.3,3.5,0.5,7.05,0.0,1.0,42.35,2.5,0.0,0.0
32,1,2025-01-01 00:27:31,2025-01-01 00:48:55,1.0,2.90,1.0,N,79,161,1,17.7,3.5,0.5,0.00,0.0,1.0,22.70,2.5,0.0,0.0
33,1,2025-01-01 00:55:38,2025-01-01 00:59:32,1.0,0.40,1.0,N,162,229,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
34,2,2025-01-01 00:32:47,2025-01-01 01:01:49,1.0,4.41,1.0,N,246,236,1,28.9,1.0,0.5,3.39,0.0,1.0,37.29,2.5,0.0,0.0
35,2,2025-01-01 00:32:04,2025-01-01 00:40:54,1.0,1.51,1.0,N,237,140,1,10.7,1.0,0.5,3.14,0.0,1.0,18.84,2.5,0.0,0.0
36,2,2025-01-01 00:53:47,2025-01-01 00:58:02,1.0,0.65,1.0,N,263,141,1,5.8,1.0,0.5,2.16,0.0,1.0,12.96,2.5,0.0,0.0
37,2,2025-01-01 00:16:55,2025-01-01 00:27:36,1.0,1.66,1.0,N,238,236,1,12.1,1.0,0.5,3.42,0.0,1.0,20.52,2.5,0.0,0.0
38,2,2025-01-01 00:39:33,2025-01-01 00:43:53,1.0,0.77,1.0,N,239,142,1,6.5,1.0,0.5,0.69,0.0,1.0,12.19,2.5,0.0,0.0
39,2,2025-01-01 00:59:29,2025-01-01 01:27:47,1.0,4.26,1.0,N,239,113,1,27.5,1.0,0.5,6.50,0.0,1.0,39.00,2.5,0.0,0.0
40,2,2025-01-01 00:15:41,2025-01-01 01:03:03,4.0,3.05,1.0,N,114,161,1,37.3,1.0,0.5,8.46,0.0,1.0,50.76,2.5,0.0,0.0
41,2,2025-01-01 00:39:26,2025-01-01 00:57:14,1.0,2.31,1.0,N,224,68,1,17.0,1.0,0.5,3.30,0.0,1.0,25.30,2.5,0.0,0.0
42,2,2025-01-01 00:07:07,2025-01-01 00:13:18,2.0,1.02,1.0,N,237,236,1,7.9,1.0,0.5,1.55,0.0,1.0,14.45,2.5,0.0,0.0
43,2,2025-01-01 00:22:56,2025-01-01 00:33:12,2.0,1.50,1.0,N,237,140,1,10.7,1.0,0.5,3.14,0.0,1.0,18.84,2.5,0.0,0.0
44,2,2025-01-01 00:43:44,2025-01-01 01:05:18,4.0,2.26,1.0,N,237,238,1,19.8,1.0,0.5,4.96,0.0,1.0,29.76,2.5,0.0,0.0
45,1,2025-01-01 00:56:12,2025-01-01 01:03:30,2.0,0.70,1.0,N,79,4,1,7.9,3.5,0.5,1.00,0.0,1.0,13.90,2.5,0.0,0.0
46,1,2025-01-01 00:24:02,2025-01-01 00:35:10,1.0,1.20,1.0,N,164,233,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
47,2,2025-01-01 00:52:53,2025-01-01 00:59:31,1.0,1.63,1.0,N,237,263,1,9.3,1.0,0.5,2.00,0.0,1.0,16.30,2.5,0.0,0.0
48,1,2025-01-01 00:13:55,2025-01-01 00:24:40,1.0,1.30,1.0,N,114,79,1,10.7,3.5,0.5,3.90,0.0,1.0,19.60,2.5,0.0,0.0
49,1,2025-01-01 00:27:34,2025-01-01 00:33:38,1.0,1.20,1.0,N,79,170,1,7.9,3.5,0.5,1.00,0.0,1.0,13.90,2.5,0.0,0.0

In [ ]:
# ver los campos de un fichero sin cargarlo (Con polars)

import polars as pl

# 0.path de los ficheros 

parquet_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/yellow_tripdata_2025-01.parquet'

# 1. Cargar el esquema del conjunto de datos
esquema = pl.read_parquet_schema(parquet_file)

# 2. Ver el resultado
#print(esquema)     # Lo muestra todo seguido
esquema             # Se ve mas claro por filas

Schema([('VendorID', Int32),
        ('tpep_pickup_datetime', Datetime(time_unit='us', time_zone=None)),
        ('tpep_dropoff_datetime', Datetime(time_unit='us', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('RatecodeID', Int64),
        ('store_and_fwd_flag', String),
        ('PULocationID', Int32),
        ('DOLocationID', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('Airport_fee', Float64),
        ('cbd_congestion_fee', Float64)])

Con polars podremos trabajar en 2 modos, modo eager (inmediato), o en modo Lazy (Plan de ejecución)

Modo eager paso a paso:

- Carga fichero
- Filtra
- crea un dataframe temporal
- agrupa
- crea otro dataframe temporal
- calcula la métrica (sum, avg, max, min, count)
- ordena
- devuelve resultado

Cada linea ejecuta el trabajo de forma inmediata (sin optimizacion global)

In [15]:
# Con este fichero taxi enero del parquet vamos a calcular la propina media y el ticket medio (el pago) por número de passajeros 
# (en NYC, el número máximo de pasajeros creo que son 9) , modo eager

import polars as pl

# 0.path de los ficheros 

parquet_file = '/Users/rogerdefez/Documents/Cursos i Llibres/Curso Barcelona Activa/2026-04-29_Python3_Ciencia-de-datos-Python-Institute-PCAD-31-Ed2/Datos_originales/yellow_tripdata_2025-01.parquet'

# 1.  carga inmediata en modo eager

df_taxi_01 = pl.read_parquet(parquet_file)

# 2. Comprobar si se ha cargado bien, visualizamos los 20 primeros
df_taxi_01.head(20)

# 3. VAmos a filtrar + agrupar + agregar + ordenar

resultado = (
    df_taxi_01
    .filter(
        (pl.col('trip_distance')>1) & 
        (pl.col('total_amount')>0) &
        (pl.col('passenger_count').is_not_null())
    )
    .group_by('passenger_count')
    .agg(
        pl.len().alias('Numero viajes'), # numero de viajes
        pl.col('trip_distance').mean().round(2).alias('distancia media')
    )
    .sort('passenger_count')
)

resultado

shape: (9, 3)
┌─────────────────┬───────────────┬─────────────────┐
│ passenger_count ┆ Numero viajes ┆ distancia media │
│ ---             ┆ ---           ┆ ---             │
│ i64             ┆ u32           ┆ f64             │
╞═════════════════╪═══════════════╪═════════════════╡
│ 0               ┆ 16141         ┆ 3.39            │
│ 1               ┆ 1644314       ┆ 4.02            │
│ 2               ┆ 297477        ┆ 4.67            │
│ 3               ┆ 66010         ┆ 4.44            │
│ 4               ┆ 42079         ┆ 4.78            │
│ 5               ┆ 13363         ┆ 3.68            │
│ 6               ┆ 8933          ┆ 3.89            │
│ 8               ┆ 4             ┆ 17.41           │
│ 9               ┆ 3             ┆ 14.86           │
└─────────────────┴───────────────┴─────────────────┘